name: weekly update

on:
  schedule:
    - cron: '0 0 * * 1'  # every monday at 00:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install deps
        run: npm ci

      - name: 'Create env file'
        run: |
          touch .env
          echo GH_PAT=${{ secrets.GITHUB_TOKEN }} >> .env

      - name: run update script
        run: npm run fetch
        working-directory: .

      - name: create or update pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: automated weekly update"
          title: "Automated weekly update"
          body: "This PR was automatically generated by the weekly workflow."
          branch: "auto/weekly-update"
          base: "main"
          add-paths: |
            public/ico/
            src/champions.json
          delete-branch: false
